# Generated by Django 4.2.7 on 2025-07-27 13:41

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='מפתח סשן')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן ב')),
            ],
            options={
                'verbose_name': 'עגלת קניות',
                'verbose_name_plural': 'עגלות קניות',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם הקטגוריה')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב')),
            ],
            options={
                'verbose_name': 'קטגוריה',
                'verbose_name_plural': 'קטגוריות',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='מספר הזמנה')),
                ('customer_name', models.CharField(max_length=100, verbose_name='שם הלקוח')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='אימייל')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='טלפון')),
                ('shipping_address', models.TextField(verbose_name='כתובת למשלוח')),
                ('city', models.CharField(max_length=50, verbose_name='עיר')),
                ('postal_code', models.CharField(max_length=10, verbose_name='מיקוד')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='סכום כולל (₪)')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='עלות משלוח (₪)')),
                ('status', models.CharField(choices=[('pending', 'ממתין לאישור'), ('confirmed', 'אושר'), ('processing', 'בעיבוד'), ('shipped', 'נשלח'), ('delivered', 'נמסר'), ('cancelled', 'בוטל')], default='pending', max_length=20, verbose_name='סטטוס')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן ב')),
            ],
            options={
                'verbose_name': 'הזמנה',
                'verbose_name_plural': 'הזמנות',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם המוצר')),
                ('description', models.TextField(verbose_name='תיאור')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='מחיר (₪)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='תמונה')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='מלאי')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('featured', models.BooleanField(default=False, verbose_name='מוצר מומלץ')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='מק״ט')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='משקל (ק״ג)')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='מידות')),
                ('warranty_months', models.PositiveIntegerField(default=12, verbose_name='אחריות (חודשים)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='נוצר ב')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='עודכן ב')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='קטגוריה')),
            ],
            options={
                'verbose_name': 'מוצר',
                'verbose_name_plural': 'מוצרים',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='כמות')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר ליחידה (₪)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order', verbose_name='הזמנה')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='מוצר')),
            ],
            options={
                'verbose_name': 'פריט בהזמנה',
                'verbose_name_plural': 'פריטים בהזמנה',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='כמות')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='נוסף ב')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.cart', verbose_name='עגלה')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='מוצר')),
            ],
            options={
                'verbose_name': 'פריט בעגלה',
                'verbose_name_plural': 'פריטים בעגלה',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
