# Generated by Django 5.0 on 2025-08-07 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_price_alter_product_sku"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
    ]
