# Generated by Django 5.0 on 2025-08-22 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_remove_product_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="show_in_gallery",
            field=models.BooleanField(default=True, verbose_name="הצג בגלריה"),
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="שם תת-הקטגוריה"),
                ),
                ("description", models.TextField(blank=True, verbose_name="תיאור")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="נוצר ב"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_categories",
                        to="products.category",
                        verbose_name="קטגוריה",
                    ),
                ),
            ],
            options={
                "verbose_name": "תת-קטגוריה",
                "verbose_name_plural": "תת-קטגוריות",
                "ordering": ["category", "name"],
                "unique_together": {("name", "category")},
            },
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="products.subcategory",
                verbose_name="תת-קטגוריה",
            ),
        ),
    ]
