# Generated by Django 5.0 on 2025-08-28 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_product_show_in_gallery_subcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="warranty_months",
        ),
    ]
